export const ApiEndpoints = {
  AUTH_LOGIN: '/api/v2/auth/login',
  AUTH_LOGOUT: '/api/v2/auth/logout',
  AUTH_ME: '/api/v2/auth/me',
  AUTH_FORGOT_PASSWORD: '/api/v2/auth/forgot-password',
  AUTH_RESET_VERIFY: '/api/v2/auth/forgot-password/verify',
  AUTH_RESET_RESEND: '/api/v2/auth/forgot-password/resend',
  AUTH_RESET_PASSWORD: '/api/v2/auth/forgot-password/reset',
  AUTH_CHANGE_PASSWORD: '/api/v2/auth/change-password',
  AUTH_PROFILE_AVATAR: '/api/v2/auth/profile/avatar',

  APP_INFO: '/api/v2/settings/app-info',
  APP_INFO_RESET: '/api/v2/settings/app-info/reset',
  APP_CONFIG: '/api/v2/settings/app-config',
  APP_CONFIG_TEST_EMAIL: '/api/v2/settings/app-config/email/test-connection',
  APP_CONFIG_SEND_TEST_EMAIL: '/api/v2/settings/app-config/email/send-test',
  APP_CONFIG_TEST_TELEGRAM: '/api/v2/settings/app-config/telegram/test-connection',
  APP_CONFIG_SEND_TEST_TELEGRAM: '/api/v2/settings/app-config/telegram/send-test',
  STORAGE_PROVIDERS: '/api/v2/settings/storage',
  STORAGE_PROVIDER: (id: string) => `/api/v2/settings/storage/${id}`,
  STORAGE_PROVIDER_TEST: (id: string) => `/api/v2/settings/storage/${id}/test-connection`,
  STORAGE_PROVIDER_SET_DEFAULT: (id: string) => `/api/v2/settings/storage/${id}/set-default`,
  STORAGE_PROVIDER_SET_ACTIVE: (id: string) => `/api/v2/settings/storage/${id}/set-active`,

  SEARCH: '/api/v2/search',
  SEARCH_ASK: '/api/v2/search/ask',
} as const
