import { DOCUMENT_SEQUENCE_STATUSES, DOCUMENT_SEQUENCE_TYPES } from '~/utils/document-sequences'
import type { FreightField, FreightModule } from './freight-modules'
import { ACTIVE_STATUS, COUNTRIES, CURRENCIES, TIMEZONES } from './freight-options'

/** Administration modules recovered from the template's admin catalog. */

type RentalFieldType = FreightField['type']
type RentalSelectOption = string | { label: string, value: string }

const f = (
  key: string,
  label: string,
  labelKm: string,
  section = 'General Information',
  sectionKm = 'ព័ត៌មានទូទៅ',
  type: RentalFieldType = 'text',
  options?: readonly RentalSelectOption[] | RentalSelectOption[],
  extra: Partial<FreightField> = {},
): FreightField => ({ key, label, labelKm, section, sectionKm, type, options, ...extra })

const col = (key: string, label: string, labelKm?: string, extra: Partial<FreightField> = {}): FreightField => ({
  key,
  label,
  labelKm: labelKm || label,
  ...extra,
})

function createModule(partial: Omit<FreightModule, 'canCreate'> & { canCreate?: boolean }): FreightModule {
  return {
    canCreate: partial.readOnly ? false : partial.canCreate !== false,
    kind: partial.kind || 'standard',
    ...partial,
  }
}

const YES_NO = ['Yes', 'No'] as const

export const adminModules: FreightModule[] = [
  createModule({
    path: '/administration/organizations',
    title: 'Organizations',
    titleKm: 'អង្គភាព',
    singular: 'Organization',
    singularKm: 'អង្គភាព',
    description: 'Legal organization, localization and default accounting context.',
    descriptionKm: 'អង្គភាពផ្លូវការ ភាសា និងបរិបទគណនេយ្យលំនាំដើម។',
    icon: 'i-lucide-landmark',
    group: 'admin',
    permission: 'admin.organization.view',
    collection: 'organizations',
    titleField: 'displayName',
    canCreate: true,
    columns: [
      col('organizationCode', 'Organization Code', 'លេខកូដអង្គភាព'),
      col('legalName', 'Legal Name', 'ឈ្មោះផ្លូវការ'),
      col('displayName', 'Display Name', 'ឈ្មោះបង្ហាញ'),
      col('taxIdentifier', 'Tax Identifier', 'លេខសម្គាល់ពន្ធ'),
      col('country', 'Country', 'ប្រទេស'),
      col('defaultCurrency', 'Default Currency', 'រូបិយប័ណ្ណលំនាំដើម'),
      col('timezone', 'Timezone', 'តំបន់ពេលវេលា'),
      col('status', 'Status', 'ស្ថានភាព'),
    ],
    fields: [
      f('organizationCode', 'Organization Code', 'លេខកូដអង្គភាព', 'General', 'ទូទៅ', 'text', undefined, { required: true }),
      f('legalName', 'Legal Name', 'ឈ្មោះផ្លូវការ', 'General', 'ទូទៅ', 'text', undefined, { required: true }),
      f('displayName', 'Display Name', 'ឈ្មោះបង្ហាញ', 'General', 'ទូទៅ'),
      f('taxIdentifier', 'Tax Identifier', 'លេខសម្គាល់ពន្ធ', 'General', 'ទូទៅ'),
      f('country', 'Country', 'ប្រទេស', 'General', 'ទូទៅ', 'select', COUNTRIES),
      f('defaultCurrency', 'Default Currency', 'រូបិយប័ណ្ណលំនាំដើម', 'General', 'ទូទៅ', 'select', CURRENCIES),
      f('timezone', 'Timezone', 'តំបន់ពេលវេលា', 'General', 'ទូទៅ', 'select', TIMEZONES),
      f('status', 'Status', 'ស្ថានភាព', 'Status', 'ស្ថានភាព', 'select', ACTIVE_STATUS),
    ],
    filters: [
      f('country', 'Country', 'ប្រទេស', '', '', 'select', COUNTRIES),
      f('status', 'Status', 'ស្ថានភាព', '', '', 'select', ACTIVE_STATUS),
    ],
  }),
  createModule({
    path: '/administration/branches',
    title: 'Branches',
    titleKm: 'សាខា',
    singular: 'Branch',
    singularKm: 'សាខា',
    description: 'Branch ownership, location and contact context.',
    descriptionKm: 'កម្មសិទ្ធិសាខា ទីតាំង និងព័ត៌មានទំនាក់ទំនង។',
    icon: 'i-lucide-git-branch',
    group: 'admin',
    permission: 'admin.organization.view',
    collection: 'branches',
    titleField: 'name',
    canCreate: true,
    columns: [
      col('branchCode', 'Branch Code', 'លេខកូដសាខា'),
      col('name', 'Name', 'ឈ្មោះ'),
      col('organizationName', 'Organization', 'អង្គភាព'),
      col('place', 'Place', 'ទីកន្លែង'),
      col('phone', 'Phone', 'ទូរស័ព្ទ'),
      col('email', 'Email', 'អ៊ីមែល'),
      col('headOffice', 'Head Office', 'ការិយាល័យកណ្តាល'),
      col('status', 'Status', 'ស្ថានភាព'),
    ],
    fields: [
      f('branchCode', 'Branch Code', 'លេខកូដសាខា', 'General', 'ទូទៅ', 'text', undefined, { required: true }),
      f('name', 'Name', 'ឈ្មោះ', 'General', 'ទូទៅ', 'text', undefined, { required: true }),
      f('organizationName', 'Organization', 'អង្គភាព', 'General', 'ទូទៅ'),
      f('place', 'Place', 'ទីកន្លែង', 'General', 'ទូទៅ'),
      f('phone', 'Phone', 'ទូរស័ព្ទ', 'General', 'ទូទៅ'),
      f('email', 'Email', 'អ៊ីមែល', 'General', 'ទូទៅ'),
      f('address', 'Address', 'អាសយដ្ឋាន', 'General', 'ទូទៅ', 'textarea', undefined, { colSpan: 2 }),
      f('headOffice', 'Head Office', 'ការិយាល័យកណ្តាល', 'Status', 'ស្ថានភាព', 'checkbox', YES_NO),
      f('status', 'Status', 'ស្ថានភាព', 'Status', 'ស្ថានភាព', 'select', ACTIVE_STATUS),
    ],
    filters: [
      f('status', 'Status', 'ស្ថានភាព', '', '', 'select', ACTIVE_STATUS),
    ],
  }),
  createModule({
    path: '/administration/users',
    title: 'Users',
    titleKm: 'អ្នកប្រើប្រាស់',
    singular: 'User',
    singularKm: 'អ្នកប្រើ',
    description: 'Manage staff access by role and department.',
    descriptionKm: 'គ្រប់គ្រងសិទ្ធិបុគ្គលិកតាមតួនាទី និងនាយកដ្ឋាន។',
    icon: 'i-lucide-users',
    group: 'admin',
    permission: 'admin.users.view',
    collection: 'users',
    titleField: 'displayName',
    columns: [
      col('userCode', 'User Code', 'លេខកូដអ្នកប្រើ'),
      col('username', 'Username', 'ឈ្មោះអ្នកប្រើ'),
      col('displayName', 'Display Name', 'ឈ្មោះបង្ហាញ'),
      col('email', 'Email', 'អ៊ីមែល'),
      col('phone', 'Phone', 'ទូរស័ព្ទ'),
      col('status', 'Status', 'ស្ថានភាព'),
      col('defaultBranch', 'Default Branch', 'សាខាលំនាំដើម'),
      col('lastLogin', 'Last Login', 'ចូលចុងក្រោយ'),
    ],
    fields: [
      f('userCode', 'User Code', 'លេខកូដអ្នកប្រើ', 'General', 'ទូទៅ'),
      f('username', 'Username', 'ឈ្មោះអ្នកប្រើ', 'General', 'ទូទៅ'),
      f('displayName', 'Display Name', 'ឈ្មោះបង្ហាញ', 'General', 'ទូទៅ'),
      f('email', 'Email', 'អ៊ីមែល', 'General', 'ទូទៅ'),
      f('telegram', 'Telegram', 'តេលេក្រាម', 'General', 'ទូទៅ'),
      f('organization', 'Organization', 'អង្គភាព', 'General', 'ទូទៅ'),
      f('branch', 'Branch', 'សាខា', 'General', 'ទូទៅ'),
      f('role', 'Role Name', 'ឈ្មោះតួនាទី', 'General', 'ទូទៅ'),
      f('status', 'Status', 'ស្ថានភាព', 'General', 'ទូទៅ', 'select', ACTIVE_STATUS),
    ],
  }),
  createModule({
    path: '/administration/roles',
    title: 'Roles & Permissions',
    titleKm: 'តួនាទី និងសិទ្ធិ',
    singular: 'Role',
    singularKm: 'តួនាទី',
    description: 'Define module permissions for rental teams.',
    descriptionKm: 'កំណត់សិទ្ធិម៉ូឌុលសម្រាប់ក្រុមជួលម៉ូតូ។',
    icon: 'i-lucide-shield-check',
    group: 'admin',
    permission: 'admin.roles.view',
    collection: 'roles',
    documentForm: 'roles',
    titleField: 'name',
    columns: [
      col('name', 'Role name', 'ឈ្មោះតួនាទី'),
      col('userCount', 'Users', 'អ្នកប្រើ'),
      col('permissionCount', 'Permissions', 'សិទ្ធិ'),
      col('status', 'Status', 'ស្ថានភាព'),
    ],
    fields: [
      f('code', 'Code', 'លេខកូដ', 'Main information', 'ព័ត៌មានទូទៅ', 'text', undefined, { required: true }),
      f('name', 'Role name', 'ឈ្មោះតួនាទី', 'Main information', 'ព័ត៌មានទូទៅ', 'text', undefined, { required: true }),
      f('status', 'Status', 'ស្ថានភាព', 'Main information', 'ព័ត៌មានទូទៅ', 'select', ACTIVE_STATUS, { colSpan: 2 }),
      f('description', 'Description', 'បរិយាយ', 'Main information', 'ព័ត៌មានទូទៅ', 'textarea', undefined, { colSpan: 2 }),
    ],
  }),
  createModule({
    path: '/administration/document-sequences',
    title: 'Document Sequences',
    titleKm: 'លំដាប់លេខឯកសារ',
    singular: 'Document Sequence',
    singularKm: 'លំដាប់ឯកសារ',
    description: 'Manage organization-scoped automatic document numbering by document type and year.',
    descriptionKm: 'គ្រប់គ្រងលេខឯកសារស្វ័យប្រវត្តិតាមអង្គភាព ប្រភេទឯកសារ និងឆ្នាំ។',
    icon: 'i-lucide-list-ordered',
    group: 'admin',
    permission: 'configuration.manage',
    collection: 'documentSequences',
    titleField: 'documentType',
    canCreate: true,
    columns: [
      col('documentType', 'Document Type', 'ប្រភេទឯកសារ'),
      col('year', 'Year', 'ឆ្នាំ'),
      col('prefix', 'Prefix', 'បុព្វបទ'),
      col('lastValue', 'Last Value', 'តម្លៃចុងក្រោយ'),
      col('paddingLength', 'Padding Length', 'ប្រវែងលេខ'),
      col('nextNumberPreview', 'Next Number Preview', 'លេខបន្ទាប់'),
      col('status', 'Status', 'ស្ថានភាព'),
    ],
    fields: [
      f('organizationName', 'Organization', 'អង្គភាព', 'General', 'ទូទៅ', 'text', undefined, { computed: true }),
      f('documentType', 'Document Type', 'ប្រភេទឯកសារ', 'General', 'ទូទៅ', 'select', DOCUMENT_SEQUENCE_TYPES, { required: true }),
      f('year', 'Year', 'ឆ្នាំ', 'General', 'ទូទៅ', 'number', undefined, { required: true }),
      f('prefix', 'Prefix', 'បុព្វបទ', 'General', 'ទូទៅ', 'text', undefined, { required: true }),
      f('lastValue', 'Starting / Last Value', 'តម្លៃចាប់ផ្តើម / ចុងក្រោយ', 'General', 'ទូទៅ', 'number', undefined, { required: true }),
      f('paddingLength', 'Padding Length', 'ប្រវែងលេខ', 'General', 'ទូទៅ', 'number', undefined, { required: true }),
      f('resetRule', 'Reset Rule', 'ការកំណត់ឡើងវិញ', 'General', 'ទូទៅ', 'select', ['Never', 'Yearly']),
      f('nextNumberPreview', 'Next Number Preview', 'លេខបន្ទាប់', 'General', 'ទូទៅ', 'text', undefined, { computed: true }),
      f('status', 'Status', 'ស្ថានភាព', 'Status', 'ស្ថានភាព', 'select', DOCUMENT_SEQUENCE_STATUSES, { required: true }),
    ],
    filters: [
      f('documentType', 'Document Type', 'ប្រភេទឯកសារ', '', '', 'select', DOCUMENT_SEQUENCE_TYPES),
      f('year', 'Year', 'ឆ្នាំ', '', '', 'select'),
      f('status', 'Status', 'ស្ថានភាព', '', '', 'select', DOCUMENT_SEQUENCE_STATUSES),
    ],
  }),
  createModule({
    path: '/administration/audit-logs',
    title: 'Audit Logs',
    titleKm: 'កំណត់ហេតុសវនកម្ម',
    singular: 'Audit Log',
    singularKm: 'កំណត់ហេតុ',
    description: 'Trace create, update, approve, send and payment actions across the system.',
    descriptionKm: 'តាមដានសកម្មភាពបង្កើត កែប្រែ អនុម័ត ផ្ញើ និងទូទាត់។',
    icon: 'i-lucide-scroll-text',
    group: 'admin',
    permission: 'admin.audit_logs.view',
    collection: 'auditLogs',
    titleField: 'action',
    readOnly: true,
    tableOnly: true,
    columns: [
      col('occurredAt', 'Date / Time', 'កាលបរិច្ឆេទ / ពេលវេលា'),
      col('user', 'User', 'អ្នកប្រើ'),
      col('eventType', 'Event Type', 'ប្រភេទព្រឹត្តិការណ៍'),
      col('action', 'Action', 'សកម្មភាព'),
      col('entityType', 'Entity Type', 'ប្រភេទអង្គភាពទិន្នន័យ'),
      col('entity', 'Entity', 'អង្គភាពទិន្នន័យ'),
      col('organizationName', 'Organization', 'អង្គភាព'),
      col('branchName', 'Branch', 'សាខា'),
      col('result', 'Result', 'លទ្ធផល'),
      col('reason', 'Reason', 'មូលហេតុ'),
      col('requestId', 'Request ID', 'លេខសំណើ'),
    ],
    fields: [
      f('occurredAt', 'Time', 'ពេលវេលា', 'Log', 'កំណត់ហេតុ', 'datetime'),
      f('user', 'User', 'អ្នកប្រើ', 'Log', 'កំណត់ហេតុ'),
      f('eventType', 'Event Type', 'ប្រភេទព្រឹត្តិការណ៍', 'Log', 'កំណត់ហេតុ'),
      f('action', 'Action', 'សកម្មភាព', 'Log', 'កំណត់ហេតុ'),
      f('entityType', 'Entity Type', 'ប្រភេទអង្គភាពទិន្នន័យ', 'Entity', 'អង្គភាពទិន្នន័យ'),
      f('entity', 'Entity', 'អង្គភាពទិន្នន័យ', 'Entity', 'អង្គភាពទិន្នន័យ'),
      f('organizationName', 'Organization', 'អង្គភាព', 'Scope', 'វិសាលភាព'),
      f('branchName', 'Branch', 'សាខា', 'Scope', 'វិសាលភាព'),
      f('result', 'Result', 'លទ្ធផល', 'Result', 'លទ្ធផល'),
      f('reason', 'Reason', 'មូលហេតុ', 'Result', 'លទ្ធផល', 'textarea'),
      f('requestId', 'Request ID', 'លេខសំណើ', 'Traceability', 'ការតាមដាន'),
      f('correlationId', 'Correlation ID', 'លេខទំនាក់ទំនង', 'Traceability', 'ការតាមដាន'),
      f('beforeData', 'Before Data', 'ទិន្នន័យមុន', 'Data', 'ទិន្នន័យ', 'textarea'),
      f('afterData', 'After Data', 'ទិន្នន័យបន្ទាប់', 'Data', 'ទិន្នន័យ', 'textarea'),
      f('metadata', 'Metadata', 'មេតាទិន្នន័យ', 'Data', 'ទិន្នន័យ', 'textarea'),
    ],
    filters: [
      f('user', 'Actor', 'អ្នកប្រើ', '', ''),
      f('eventType', 'Event Type', 'ប្រភេទព្រឹត្តិការណ៍', '', ''),
      f('entityType', 'Entity Type', 'ប្រភេទអង្គភាពទិន្នន័យ', '', ''),
      f('organizationName', 'Organization', 'អង្គភាព', '', ''),
      f('branchName', 'Branch', 'សាខា', '', ''),
      f('result', 'Result', 'លទ្ធផល', '', '', 'select', ['SUCCESS', 'FAILED', 'DENIED']),
    ],
  }),
]

/** Field helper re-export keeps admin module field types explicit. */
export type { FreightField }
