"""initial schema

Revision ID: ab57577973e4
Revises: 
Create Date: 2026-09-01 14:32:14.885184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab57577973e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('entity_label', sa.String(length=200), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('document_sequences',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=False),
    sa.Column('prefix', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('padding_length', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_sequences_document_type'), 'document_sequences', ['document_type'], unique=True)
    op.create_table('export_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource', sa.String(length=60), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_resource'), 'export_jobs', ['resource'], unique=False)
    op.create_index(op.f('ix_export_jobs_status'), 'export_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_export_jobs_user_id'), 'export_jobs', ['user_id'], unique=False)
    op.create_table('motorcycles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('plate', sa.String(length=60), nullable=True),
    sa.Column('chassis_no', sa.String(length=80), nullable=True),
    sa.Column('engine_no', sa.String(length=80), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('three_day_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('weekly_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('asset_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motorcycles_code'), 'motorcycles', ['code'], unique=True)
    op.create_index(op.f('ix_motorcycles_plate'), 'motorcycles', ['plate'], unique=False)
    op.create_index(op.f('ix_motorcycles_status'), 'motorcycles', ['status'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('queue', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('rental_customers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('identity_type', sa.String(length=40), nullable=True),
    sa.Column('identity_number', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_customers_code'), 'rental_customers', ['code'], unique=True)
    op.create_index(op.f('ix_rental_customers_identity_number'), 'rental_customers', ['identity_number'], unique=False)
    op.create_index(op.f('ix_rental_customers_phone'), 'rental_customers', ['phone'], unique=False)
    op.create_index(op.f('ix_rental_customers_status'), 'rental_customers', ['status'], unique=False)
    op.create_table('rental_expenses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('expense_no', sa.String(length=60), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expense_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_expenses_date'), 'rental_expenses', ['date'], unique=False)
    op.create_index(op.f('ix_rental_expenses_expense_no'), 'rental_expenses', ['expense_no'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('page_access', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('storage_providers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('allowed_file_types', sa.JSON(), nullable=True),
    sa.Column('access_mode', sa.String(length=20), nullable=False),
    sa.Column('upload_path_pattern', sa.String(length=200), nullable=False),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=300), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('bucket', sa.String(length=120), nullable=True),
    sa.Column('access_key', sa.String(length=200), nullable=True),
    sa.Column('secret_key', sa.String(length=300), nullable=True),
    sa.Column('public_url', sa.String(length=300), nullable=True),
    sa.Column('path_style', sa.Boolean(), nullable=True),
    sa.Column('folder_id', sa.String(length=120), nullable=True),
    sa.Column('client_id', sa.String(length=200), nullable=True),
    sa.Column('client_secret', sa.String(length=300), nullable=True),
    sa.Column('credential_status', sa.String(length=20), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('sync_schedule', sa.String(length=60), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_progress',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('related_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_progress_status'), 'task_progress', ['status'], unique=False)
    op.create_index(op.f('ix_task_progress_task_type'), 'task_progress', ['task_type'], unique=False)
    op.create_index(op.f('ix_task_progress_user_id'), 'task_progress', ['user_id'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('rental_no', sa.String(length=60), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('motorcycle_id', sa.String(length=40), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('motorcycle', sa.String(length=200), nullable=False),
    sa.Column('plate', sa.String(length=60), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('rate_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('rental_charge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('additional_charges', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('return_note', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overdue_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['rental_customers.id'], ),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_customer_id'), 'rentals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rentals_due_date'), 'rentals', ['due_date'], unique=False)
    op.create_index(op.f('ix_rentals_motorcycle_id'), 'rentals', ['motorcycle_id'], unique=False)
    op.create_index(op.f('ix_rentals_rental_no'), 'rentals', ['rental_no'], unique=True)
    op.create_index(op.f('ix_rentals_start_date'), 'rentals', ['start_date'], unique=False)
    op.create_index(op.f('ix_rentals_status'), 'rentals', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('page_access', sa.JSON(), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('password_reset_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_challenges_code_hash'), 'password_reset_challenges', ['code_hash'], unique=False)
    op.create_index(op.f('ix_password_reset_challenges_user_id'), 'password_reset_challenges', ['user_id'], unique=False)
    op.create_index('ix_prc_user_active', 'password_reset_challenges', ['user_id', 'consumed_at'], unique=False)
    op.create_table('refresh_token_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_sessions_family_id'), 'refresh_token_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_sessions_jti'), 'refresh_token_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_token_sessions_user_id'), 'refresh_token_sessions', ['user_id'], unique=False)
    op.create_table('rental_charges',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('charge_no', sa.String(length=60), nullable=False),
    sa.Column('rental_id', sa.String(length=40), nullable=False),
    sa.Column('charge_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('charge_to_customer', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_charges_charge_no'), 'rental_charges', ['charge_no'], unique=True)
    op.create_index(op.f('ix_rental_charges_rental_id'), 'rental_charges', ['rental_id'], unique=False)
    op.create_table('rental_payments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('payment_no', sa.String(length=60), nullable=False),
    sa.Column('rental_id', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=160), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_payments_payment_no'), 'rental_payments', ['payment_no'], unique=True)
    op.create_index(op.f('ix_rental_payments_rental_id'), 'rental_payments', ['rental_id'], unique=False)
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index(op.f('ix_telegram_link_codes_user_id'), 'telegram_link_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_link_codes_user_id'), table_name='telegram_link_codes')
    op.drop_table('telegram_link_codes')
    op.drop_index(op.f('ix_rental_payments_rental_id'), table_name='rental_payments')
    op.drop_index(op.f('ix_rental_payments_payment_no'), table_name='rental_payments')
    op.drop_table('rental_payments')
    op.drop_index(op.f('ix_rental_charges_rental_id'), table_name='rental_charges')
    op.drop_index(op.f('ix_rental_charges_charge_no'), table_name='rental_charges')
    op.drop_table('rental_charges')
    op.drop_index(op.f('ix_refresh_token_sessions_user_id'), table_name='refresh_token_sessions')
    op.drop_index(op.f('ix_refresh_token_sessions_jti'), table_name='refresh_token_sessions')
    op.drop_index(op.f('ix_refresh_token_sessions_family_id'), table_name='refresh_token_sessions')
    op.drop_table('refresh_token_sessions')
    op.drop_index('ix_prc_user_active', table_name='password_reset_challenges')
    op.drop_index(op.f('ix_password_reset_challenges_user_id'), table_name='password_reset_challenges')
    op.drop_index(op.f('ix_password_reset_challenges_code_hash'), table_name='password_reset_challenges')
    op.drop_table('password_reset_challenges')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rentals_status'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_start_date'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_rental_no'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_motorcycle_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_due_date'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_customer_id'), table_name='rentals')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_task_progress_user_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_task_type'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_status'), table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_table('storage_providers')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_rental_expenses_expense_no'), table_name='rental_expenses')
    op.drop_index(op.f('ix_rental_expenses_date'), table_name='rental_expenses')
    op.drop_table('rental_expenses')
    op.drop_index(op.f('ix_rental_customers_status'), table_name='rental_customers')
    op.drop_index(op.f('ix_rental_customers_phone'), table_name='rental_customers')
    op.drop_index(op.f('ix_rental_customers_identity_number'), table_name='rental_customers')
    op.drop_index(op.f('ix_rental_customers_code'), table_name='rental_customers')
    op.drop_table('rental_customers')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_motorcycles_status'), table_name='motorcycles')
    op.drop_index(op.f('ix_motorcycles_plate'), table_name='motorcycles')
    op.drop_index(op.f('ix_motorcycles_code'), table_name='motorcycles')
    op.drop_table('motorcycles')
    op.drop_index(op.f('ix_export_jobs_user_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_status'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_resource'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_document_sequences_document_type'), table_name='document_sequences')
    op.drop_table('document_sequences')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
